name: Java CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven Wrapper
        run: ./mvnw test -B
      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1